src/Mejenguitas_UI/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class ComentarioController : Controller
    {
        IJuegoRepository juegoRepository;
        IComentarioRepository comentarioRepository;

        public ComentarioController(IJuegoRepository juegoRepo, IComentarioRepository comentarioRepo)
        {
            juegoRepository = juegoRepo;
            comentarioRepository = comentarioRepo;
        }

        public ActionResult List(int idJuego = 0)
        {
            if (idJuego == 0)
            {
                return View(juegoRepository.Juegos.FirstOrDefault(j => j.Fecha >= DateTime.Now ));
            }
            else
            {
                return View(juegoRepository.Juegos.FirstOrDefault(j => j.Id == idJuego));
            }
        }

        [HttpPost]
        public ActionResult Add(int idJuego, string texto)
        {
            if (!texto.Equals(string.Empty))
            {
                Comentario nuevoComentario = new Comentario();
                nuevoComentario.IdJuego = idJuego;
                
                int idJugador = 0;
                if (Session["idJugador"] != null)
                    idJugador = Int32.Parse(Session["idJugador"].ToString());

                nuevoComentario.IdJugador = idJugador;
                nuevoComentario.IdJuego = idJuego;
                nuevoComentario.Fecha = DateTime.Now;
                nuevoComentario.Texto = texto;

                comentarioRepository.Guardar(nuevoComentario);
                TempData["valComentario"] = string.Format("Se agregó el comentario exitosamente");
            }
            else
            {
                TempData["valComentario"] = "Ingrese el texto del comentario";
            }
            return RedirectToAction("Index","Mejengas",new{idJuego});
        }
    }
}

src/Mejenguitas_UI/Controllers/GaleriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class GaleriaController : Controller
    {
        IJuegoRepository repository;

        public GaleriaController(IJuegoRepository repo)
        {
            repository = repo;
        }

        public ActionResult List(int idJuego = 0)
        {
            Juego juego = null;
            if (idJuego == 0)
            {
                juego = repository.Juegos.FirstOrDefault(j => j.Fecha >= DateTime.Now);
                if (juego != null)
                    return View(juego.Galerias);
                else
                    return View(new HashSet<Galeria>());
            }
            else
            {
                return View(repository.Juegos.FirstOrDefault(j => j.Id == idJuego).Galerias);
            }
        }

        public FileContentResult ObtenerImagen(int idJuego, int idGaleria)
        {
            Galeria galeria = repository.Juegos.FirstOrDefault(j => j.Id == idJuego).Galerias.FirstOrDefault(g => g.Id == idGaleria);
            if (galeria != null && galeria.Objecto != null && galeria.MimeTypeObjeto != string.Empty)
                return File(galeria.Objecto, galeria.MimeTypeObjeto);
            return null;
        }
    }
}

src/Mejenguitas_UI/Controllers/JugadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class JugadorController : Controller
    {
        IJugadorRepository repository;

        public JugadorController(IJugadorRepository repo)
        {
            repository = repo;
        }

        public FileContentResult ObtenerImagen(int idJugador)
        {
            Jugador jugador = repository.Jugadores.FirstOrDefault(j => j.Id == idJugador);
            if (jugador != null && jugador.Avatar != null && jugador.AvatarMimeType != null)
                return File(jugador.Avatar, jugador.AvatarMimeType);
            return null;
        }

    }
}

src/Mejenguitas_UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- Le styles -->
    @Styles.Render("~/Content/css")
    <link href="~/Content/bootstrap/bootstrap.min.css" rel="stylesheet">

    <style>
        body {
            padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
        }
    </style>
</head>
<body>
    <div class="container ">
        <div class="row page-header">
            <div class="col-xs-9 ">
                @{Html.RenderAction("List", "Galeria");}
            </div>
            <div class="col-xs-3">
                <div class="row">
                    <div class="pull-right">
                        @if (Request.IsAuthenticated)
                        {                                                     
                            @Html.ActionLink("Logout", "LogOut", new { controller = "Login" })
                        }
                        else
                        {
                            @Html.ActionLink("Login", "LoginJugador", new { controller = "Login" })
                        }
                        @Html.ActionLink("Admin", "List", new { area = "Administration", controller = "Juego", admin = true })
                    </div>
                </div>
                <div class="row">
                    <div class="pull-right">
                        @if (@Session["nombreJugador"] != null)
                        { 
                            <p>
                                <b>Bienvenido @Session["nombreJugador"]</b>
                            </p>                                                  
                        }
                        @if (@Session["idJugador"] != null)
                        { 
                            <p class="pull-right">
                                <img width="100" height="100" src="@Url.Action("ObtenerImagen", "Jugador", new { idJugador = @Session["idJugador"] })"/>
                            </p>
                        }
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div style="height:588px; width:940px">
                @RenderBody()
            </div>
        </div>
        <div class="row">
            <div class="col-xs-2">
                @{Html.RenderAction("List", "Juego");}
            </div>
            <div class="col-xs-7">
            </div>
            <div class="col-xs-3">
                @{Html.RenderAction("List", "Comentario");}
            </div>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Site")
    @Scripts.Render("~/Scripts/Mejengas.js")
    @RenderSection("scripts", required: false)
    

</body>

</html>