src/Mejenguitas_UI/Areas/Administration/Controllers/JuegoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Areas.Administration.Controllers
{
    [Authorize]
    public class JuegoController : Controller
    {
        private IJuegoRepository repository;

        public JuegoController(IJuegoRepository repo)
        {
            repository = repo;
        }

        #region CRUD Methods
        public ViewResult List()
        {
            return View(repository.Juegos.OrderByDescending(j=>j.Fecha));
        }

        public ActionResult Edit(int id)
        {
            Juego juego = repository.Juegos.FirstOrDefault(p => p.Id == id);
            return View(juego);
        }

        [HttpPost]
        public ActionResult Edit(Juego juego)
        {
            bool isNew = juego.Id == 0;
            if (ModelState.IsValid)
            {
                repository.Guardar(juego);
                TempData["message"] = string.Format("El partido para la fecha {0} fue salvado.", juego.Fecha);
                if (isNew)
                    return RedirectToAction("List");
            }

            return View(juego);
        }

        public ViewResult Create()
        {
            return View("Edit", new Juego() {  Fecha = DateTime.Now});
        }

        public ActionResult Delete(int id)
        {

            if (repository.Eliminar(id))
            {
                TempData["message"] = "Se elimino el juego exitosamente";
            }
            else
                TempData["message"] = "Sorry, El juego no fue eliminado..!! :)";

            return RedirectToAction("List");

        }

        #endregion

        #region Others
        public FileContentResult ObtenerImagen(int idJuego, int idGaleria)
        {
            Galeria g = repository.Juegos.FirstOrDefault(j => j.Id == idJuego).Galerias.FirstOrDefault(ga => ga.Id == idGaleria);
            if (g != null && g.Objecto != null && g.MimeTypeObjeto != string.Empty)
                return File(g.Objecto, g.MimeTypeObjeto);
            return null;
        }
        #endregion
    }
}

src/Mejenguitas_UI/Controllers/JuegoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;

namespace Mejenguitas_UI.Controllers
{
    public class JuegoController : Controller
    {
        private IJuegoRepository repository;

        public JuegoController(IJuegoRepository repo)
        {
            repository = repo;
        }

        public ActionResult List()
        {
            return View(repository.Juegos.OrderByDescending(j => j.Fecha).Take(3));
        }
    }
}

src/Mejenguitas_UI/Controllers/MejengasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;
using Mejenguitas_UI.Models;

namespace Mejenguitas_UI.Controllers
{
    public class MejengasController : Controller
    {
        private IJuegoRepository juegoRepository;
        private IJuegoJugadorRepository juegoJugadorRepository;
        private IJugadorRepository jugadorRepository;
        //
        // GET: /Mejengas/
        public MejengasController(IJuegoRepository juegoRepo, IJugadorRepository jugadorRepo, IJuegoJugadorRepository juegoJugadorRepo)
        {
            juegoRepository = juegoRepo;
            juegoJugadorRepository = juegoJugadorRepo;
            jugadorRepository = jugadorRepo;

        }

        public ActionResult Index(int idJuego = 0)
        {
            int idJugador = 0;
            if (Session["idJugador"] != null)
                idJugador = Int32.Parse(Session["idJugador"].ToString());

            Juego juegoActual = null;
            bool estaInscrito = false;
            List<JuegoJugador> jugadoresInscritos = new List<JuegoJugador>();
            if (idJuego == 0)
            {
                //Get the next game
                juegoActual = juegoRepository.Juegos.FirstOrDefault(j => j.Fecha >= DateTime.Now);
            }
            else
            {
                juegoActual = juegoRepository.Juegos.FirstOrDefault(j => j.Id == idJuego);
            }

            if (juegoActual != null)
            {
                if (idJugador != 0)
                {
                    estaInscrito = juegoJugadorRepository.JuegosJugadores.FirstOrDefault(jj => jj.IdJugador == idJugador && jj.IdJuego == juegoActual.Id && jj.EsInvitado == false) == null ? false : true;
                }

                if (juegoActual != null)
                    jugadoresInscritos = juegoJugadorRepository.JuegosJugadores.Where(jj => jj.IdJuego == juegoActual.Id).ToList();
            }

            return View(new JuegoJugadorViewModel
            {
                Juego = juegoActual,
                JugadoresInscritos = jugadoresInscritos,
                EstaInscrito = estaInscrito,
                IdJugador = idJugador,
                Jugadores = jugadorRepository.Jugadores.ToList()
            });
        }

        #region Others
        public FileContentResult ObtenerImagen(int idJugador, bool esInvitado)
        {
            Jugador g = jugadorRepository.Jugadores.FirstOrDefault(j => j.Id == idJugador); ;
            if (g != null && g.Avatar != null && g.AvatarMimeType != string.Empty)
                return File(g.Avatar, g.AvatarMimeType);
            return null;
        }
        #endregion
    }
}

src/Mejenguitas_UI/Views/Juego/List.cshtml
@model IQueryable<Mejenguitas.Domain.Entities.Juego>

@{
    Layout = null;
}

<h4>Juegos</h4>
<hr />

@if (@Model.Count() > 0)
{
    foreach (var juego in @Model)
    {
    <div class="row">
        <div class="col-xs-12">
            <a href='@Url.Action("Index", "Mejengas", new { idJuego = juego.Id })' style="text-decoration:none">
                <p>
                    @juego.Fecha.ToString()
                </p>    
                <p>
                    @juego.Lugar
                </p>                
                <p>
                    @switch (@juego.EquipoGanador)
                    {
                        case 0:                     
                            @:Juego Pendiente
                            break;
                        case 1: 
                            @:Gana Equipo Rojo
                            break;
                        case 2: 
                            @:Gana Equipo Blanco            
                            break;
                        case 3: 
                            @:Juego Empatado           
                            break;
                    }
                </p>
                @if (juego.EquipoGanador != 0)
                {
                    <p>
                        @juego.Resultado
                    </p>
                }
            </a>
        </div>
    </div>
    <hr />
    }    
}
else
{
    <div class="cl-xs-12">
        No hay Juegos registrados
    </div>
}