src/Mejenguitas_UI/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class ComentarioController : Controller
    {
        IJuegoRepository juegoRepository;
        IComentarioRepository comentarioRepository;

        public ComentarioController(IJuegoRepository juegoRepo, IComentarioRepository comentarioRepo)
        {
            juegoRepository = juegoRepo;
            comentarioRepository = comentarioRepo;
        }

        public ActionResult List(int idJuego = 0)
        {
            if (idJuego == 0)
            {
                return View(juegoRepository.Juegos.FirstOrDefault(j => j.Fecha >= DateTime.Now ));
            }
            else
            {
                return View(juegoRepository.Juegos.FirstOrDefault(j => j.Id == idJuego));
            }
        }

        [HttpPost]
        public ActionResult Add(int idJuego, string texto)
        {
            if (!texto.Equals(string.Empty))
            {
                Comentario nuevoComentario = new Comentario();
                nuevoComentario.IdJuego = idJuego;
                
                int idJugador = 0;
                if (Session["idJugador"] != null)
                    idJugador = Int32.Parse(Session["idJugador"].ToString());

                nuevoComentario.IdJugador = idJugador;
                nuevoComentario.IdJuego = idJuego;
                nuevoComentario.Fecha = DateTime.Now;
                nuevoComentario.Texto = texto;

                comentarioRepository.Guardar(nuevoComentario);
                TempData["valComentario"] = string.Format("Se agregó el comentario exitosamente");
            }
            else
            {
                TempData["valComentario"] = "Ingrese el texto del comentario";
            }
            return RedirectToAction("Index","Mejengas",new{idJuego});
        }
    }
}

src/Mejenguitas_UI/Controllers/JugadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class JugadorController : Controller
    {
        IJugadorRepository repository;

        public JugadorController(IJugadorRepository repo)
        {
            repository = repo;
        }

        public FileContentResult ObtenerImagen(int idJugador)
        {
            Jugador jugador = repository.Jugadores.FirstOrDefault(j => j.Id == idJugador);
            if (jugador != null && jugador.Avatar != null && jugador.AvatarMimeType != null)
                return File(jugador.Avatar, jugador.AvatarMimeType);
            return null;
        }

    }
}

src/Mejenguitas_UI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mejenguitas_UI.Models;
using Mejenguitas_UI.Infrastructure.Abstract;
using Mejenguitas.Domain.Abstract;
using Mejenguitas.Domain.Entities;

namespace Mejenguitas_UI.Controllers
{
    public class LoginController : Controller
    {
        IAuthProvider authProvider;
        
        public LoginController(IAuthProvider auth)
        {
            authProvider = auth;            
        }

        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(LoginViewModel model, string returnUrl, bool admin = false)
        {
            if (ModelState.IsValid)
            {
                Jugador jugador = authProvider.Authenticate(model.Correo, model.Contrasenna);
                if (jugador != null)
                {                    
                    if (admin.Equals(true))
                    {
                        if (jugador.Administrador.Equals(false))
                        {
                            ModelState.AddModelError("", "No tiene acceso al area de administración");
                            return View();   
                        }
                    }                    

                    Session["idJugador"] = jugador.Id;
                    Session["nombreJugador"] = jugador.Nombre;                    
                    return Redirect(returnUrl ?? Url.Action("Index", "Mejengas"));
                }
                else
                {
                    ModelState.AddModelError("", "Correo Electrónico o Contraseña incorrectos");
                    return View();
                }
            }
            else
            {
                return View();
            }
        }

        [Authorize]
        public ActionResult LoginJugador()
        {
            return RedirectToAction("Index", "Mejengas");
        }

        public ActionResult LogOut() 
        {
            authProvider.LogOut();
            Session["idJugador"] = null;
            Session["nombreJugador"] = null;
            return RedirectToAction("Index", "Mejengas");
        }
    }
}

src/Mejenguitas_UI/Views/Comentario/List.cshtml
@model Mejenguitas.Domain.Entities.Juego

@{
    Layout = null;
}

<h4>Comentarios</h4>
<hr />

@if (@Model != null && @Model.Comentarios.Count() > 0)
{
    <div class="cl-xs-12">
        @foreach (var comentario in @Model.Comentarios)
        { 
            <div class="row">
                <div class="col-xs-12">
                    <p>
                        <img width="50" height="50" src="@Url.Action("ObtenerImagen", "Jugador", new { idJugador = @comentario.IdJugador })"/>
                    </p>
                    <p>
                        @comentario.Texto
                    </p>
                    <p>
                        @comentario.Fecha.ToString()
                    </p>
                </div>
            </div>
            <hr />            
        }
    </div>    
}
else
{
    <div class="cl-xs-12">
        No hay comentarios registrados
    </div>
    <hr />
}
@if (Model != null)
{
    <div class="row">
        @if (!Request.IsAuthenticated)
        {
            <div class="pull-right">
                @Html.ActionLink(" ", "LoginJugador", "Login", null, new { @class = "glyphicon glyphicon-plus-sign", @title = "Agregar" })
            </div>
        }
        else
        {
            using (Html.BeginForm("Add", "Comentario", FormMethod.Post))
            {
            @Html.Hidden("idJuego", @Model.Id)
            <div class="col-xs-10">
                <textarea name="Texto"></textarea>
            </div>
            <div class="col-xs-2">
                <a href="#" class="glyphicon glyphicon-floppy-disk" onclick="$(this).closest('form').submit()" title="Guardar"></a>
            </div>       
            }
        }
    </div>
}